# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
                    avatar:
                        quality: 75
                        filters:
                            thumbnail:
                                        size:          [200, 200]
                                        mode:          outbound
        
                    miniavatar:
                        quality: 75
                        filters:
                            thumbnail:
                                        size:          [50, 50]
                                        mode:          outbound
        
                    minithumb:
                        quality: 75
                        filters:
                            thumbnail:
                                        size:          [60, 40]
                                        mode:          outbound
        
                    thumb:
                        quality: 75
                        filters:
                            thumbnail:
                                        size:          [360, 230]
                                        mode:          outbound

                    medium:
                        quality: 75
                        filters:
                            thumbnail:
                                        size:          [800, 530]
                                        mode:          outbound


